### ISSUE TITLE
Errors upon trying to launch

### ISSUE THREAD

**Issue by Rowdy09** [Zayveeo5e/NP.VanillaPlus#10]
I get two errors in my command prompt when trying to launch.

[SCRIPT UI] [errr] COMPILE ERROR Undefined variable "Progression_GetPreference"
[SCRIPT UI] [errr] ui/menu_lobby.nut line [233] column [42]

I followed this tutorial here "https://www.youtube.com/watch?v=haDDq0BGbhc" and unable to find anyone else with this error online.

thank you for helping! :)

**Comment by Jan200101** [comment]
The video is out of date, follow the tutorial in the README.

**Comment by itscynxx** [comment]
@Rowdy09 are you still having issues or have you followed the instructions in the README?

Alternatively, if you really wanted a video guide, here's an up to date one: https://www.youtube.com/watch?v=1g_0y_bQxqc&t=72s&pp=ygUUcGVuZ29vbiB2YW5pbGxhIHBsdXM%3D

**Comment by CoolDawg08** [comment]
Hello, I'm having the same problem, I've followed the README instructions perfectly, and it works on my computer, but not on my laptop. Assistance would be appreciated.

**Comment by itscynxx** [comment]
@CoolDawg08 can you open your own issue and upload a log (the furthest down file in R2Titanfall/logs

**Comment by itscynxx** [comment]
This issue is about a month without a response, the issue is simply that the video was out of date

Please watch the video provided earlier, or follow the settings in the README, either on GitHub or on Thunderstore
