### ISSUE TITLE
Cannot join any games and northstar profiles are not respected.

### ISSUE THREAD

**Issue by Footsiefat** [Zayveeo5e/NP.VanillaPlus#14]
Nslog: [nslog2023-11-06 23-03-37.txt](https://github.com/Zayveeo5e/NP.VanillaPlus/files/13265203/nslog2023-11-06.23-03-37.txt)
OS: Arch Linux
Proton version: Proton GE
Launch args: `LD_PRELOAD="$LD_PRELOAD:/usr/\$LIB/libgamemode.so.0" LFX=1 gamemoderun %command% -noborder -windowed -novid -northstar -norestrictservercommands -profile=R2Titanfall`
Files:  [titanfall_file_tree.txt](https://github.com/Zayveeo5e/NP.VanillaPlus/files/13265223/titanfall_file_tree.txt)

After updating (VanillaPlus) semi-recently I found it was booting into Northstar instead, no longer respecting my launch arguments. VanillaPlus does launch if I install it to the default profile location, but I cannot join any games and is stuck on "connecting to match".

In attempts to fix this I re-installed Northstar (v1.19.11) and VanillaPlus(v2.2), with Northstar overriding existing files and VanillaPlus being installed to a fresh folder to no avail.

**Comment by Kyr4l** [comment]
steam or lutris ?

**Comment by Footsiefat** [comment]
Confirmed problem with Titanfall or northstar. Closing
