### ISSUE TITLE
Can this get you banned?

### ISSUE THREAD

**Issue by Desoroxxx** [Zayveeo5e/NP.VanillaPlus#16]
As the title says

**Comment by itscynxx** [comment]
There are no reports of it getting you banned, additionally it'd be a little silly if it could (on Respawn/EA's end) as the cheats you can make via Northstar are much worse (as in bad to use, not as in bad to fight against) than ones available via other external programs designed for cheating

Especially things like model replacements have already been possible (and done) on vanilla for years with vpk modding

As well as EA/Respawn actually does close to zero moderation on vanilla, mostly being done by fairfight (which isn't too good)

**Comment by Desoroxxx** [comment]
Thanks
