### ISSUE TITLE
#Authentication_Failed_Header error upon launch for v1.3.3

### ISSUE THREAD

**Issue by Holioptic** [Zayveeo5e/NP.VanillaPlus#17]
My game has been showing this error ever since I got VP, I can ignore it by clicking "OK" but it's still very annoying. Assistance would be appreciated.
![Screenshot (44)](https://github.com/Zayveeo5e/NP.VanillaPlus/assets/69056998/d01cafca-f1fa-426e-8639-ff99b1d80c70)
here is my most recent log if you need it
[nslog2023-11-11 19-50-42.txt](https://github.com/Zayveeo5e/NP.VanillaPlus/files/13327028/nslog2023-11-11.19-50-42.txt)

**Comment by itscynxx** [comment]
Update vanilla+ 
This is due to the pre 2.0 versions still having some stuff for Northstar auth in them (which fails, as it's supposed to in order to make vanilla work) whereas it's entirely removed in 2.0 (as Northstar.Client is no longer required)

**Comment by itscynxx** [comment]
Closing as stale 
Solution, if not fixed as of closure, is updating VanillaPlus
Additionally, if not updated recently, updating Northstar
