### ISSUE TITLE
Reenable mod

### ISSUE THREAD

**Issue by BigEmster** [Zayveeo5e/NP.VanillaPlus#19]
I've disabled the mod, in turn removing the UI that would be used to reenable it. Is there a workaround for this?

**Comment by itscynxx** [comment]
In the future, don't do that :P

But yeah, go to `Titanfall2/R2Titanfall`, find `enabledmods.json`, find the entry for `VanillaPlus`, and change `false` to `true`

**Comment by BigEmster** [comment]
ok thx lmao
