### ISSUE TITLE
my mod isnt modding

### ISSUE THREAD

**Issue by pluhmaster69** [Zayveeo5e/NP.VanillaPlus#22]
![imagen_2024-11-30_183619661](https://github.com/user-attachments/assets/91050cd9-bb48-48f6-9b8f-2624d80c50fc)
basically the menu isnt loading (im using flight core btw)

**Comment by NachosChipeados** [comment]
You have an outdated vanilla+ version. Try using the newest release: https://github.com/Zayveeo5e/NP.VanillaPlus/releases/tag/v2.4.2

**Comment by pluhmaster69** [comment]
thanks :)
