### ISSUE TITLE
Stuck during Startup due to Compile Error 

### ISSUE THREAD

**Issue by RoboterFreund** [Zayveeo5e/NP.VanillaPlus#23]
The Error occurred during Startup of the Game. Acording to the Ns Terminal is it due a Compile Error 

Ns version Using: 1.29.0
Mod version Using: 2.4.1
Tested Versions: 2.4 , 2.3 (both versions with the Same Error)

![image](https://github.com/user-attachments/assets/ebb58d00-266d-4833-9b52-da5d05e16d73)

**Comment by NachosChipeados** [comment]
You have an outdated vanilla+ version. Try using the newest release: https://github.com/Zayveeo5e/NP.VanillaPlus/releases/tag/v2.4.2
