### ISSUE TITLE
Cannot connect to online servers

### ISSUE THREAD

**Issue by ahtla** [Zayveeo5e/NP.VanillaPlus#4]
After installing - the game opens up fine. It shows Vanilla + along with my client side mods enabled in the mods tab. I hit launch multiplayer and everything seems to connect fine. Then start matchmaking and it works. But once it finds a server it stays on the "connecting to server" screen indefinitely and will not connect.
I have tried a private match too where the same issues comes up

**Comment by itscynxx** [comment]
@ahtla if youre launching via launch args add the `-norestrictservercommands` launch option
this is updated in the repo, but not on the thunderstore page

**Comment by Zayveeo5e** [comment]
Added to thunderstore

**Comment by ahtla** [comment]
Thank you!
