### ISSUE TITLE
nothing happens when game launches

### ISSUE THREAD

**Issue by roigaming81** [Zayveeo5e/NP.VanillaPlus#5]
![image](https://github.com/Zayveeo5e/NP.VanillaPlus/assets/48147849/64831b89-7cda-432a-9939-cc4e8b929565)

closing the console does nothing.

**Comment by Zayveeo5e** [comment]
what other mods are installed?

**Comment by roigaming81** [comment]
> what other mods are installed?

only the default northstar and vanilla+
![image](https://github.com/Zayveeo5e/NP.VanillaPlus/assets/48147849/215d22eb-acd1-428e-b883-43e774a3603b)

**Comment by itscynxx** [comment]
> > what other mods are installed?
> 
> only the default northstar and vanilla+ ![image](https://user-images.githubusercontent.com/48147849/268995368-215d22eb-acd1-428e-b883-43e774a3603b.png)

Hello, this wont work as vtol doesnt support the way vanillaplus works by default

either delete `northstar.custom` and `northstar.customservers` and use vtol (though this may result in vtol automatically reinstalling these when finding they dont exist), or follow the mod description

**Comment by itscynxx** [comment]
Is this still an issue? if not, I'd like to close it

If there's still no response in a few days, I'll probably close as stale, but would like an actual resolution

**Comment by itscynxx** [comment]
Closing as its been 1+ months since last response
If you still have issues, please re open the issue, or open another issue and I'll happily help you
