### ISSUE TITLE
Main menu fails to load: `Undefined variable "Progression_GetPreference"`

### ISSUE THREAD

**Issue by SilverAndro** [Zayveeo5e/NP.VanillaPlus#7]
VanillaPlus: `1.3.4`
Northstar: Manual install proccess, `1.19.8`
Titanfall 2: Installed through steam, build id `10350970`

Main menu fails to load when launching VanillaPlus, complaining about an undefined variable in the console
```
[2023-10-15] [14:28:38] [NORTHSTAR] [info] Building custom scripts.rson
[2023-10-15] [14:28:38] [SCRIPT UI] [error] COMPILE ERROR Undefined variable "Progression_GetPreference"
[2023-10-15] [14:28:38] [SCRIPT UI] [error] ui/menu_lobby.nut line [233] column [42]
```
[Full log (download)](https://github.com/Zayveeo5e/NP.VanillaPlus/files/12910397/nslog2023-10-15.14-35-14.txt)

**Comment by itscynxx** [comment]
you installed the mod version into the packages directory
install it in the mods directory

2.0 is also out on the repo, you can download the mod version from `repo/mods/NP.VanillaPlus` if you'd like to use that, or you can download the [2.0 release](https://github.com/Zayveeo5e/NP.VanillaPlus/releases/tag/v2.0) and extract its contents to the Titanfall2 directory

**Comment by SilverAndro** [comment]
> you installed the mod version into the packages directory
> install it in the mods directory

Was following the README instructions at the time

Both changing it to mods and upgrading to 2.0 worked, thanks much
